name: Run Next.js development server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-dev-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Node.js with the specified version
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'  # Replace with the desired Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Next.js development server
      - name: Run Next.js development server
        run: npm run dev
