name: Run Next.js development server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-dev-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Node.js with the latest LTS version
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts' # This installs the latest LTS version of Node.js

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Next.js development server
      - name: Run Next.js development server
        run: npm run dev
