name: Run Next.js development server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-dev-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Detect package manager and set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Or specify the version you need

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Next.js development server
      - name: Run Next.js development server
        run: npm run dev
